[package]
name = "py-declare"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
py-ir = { path = "../py-ir" }
py-lex = { path = "../py-lex", default-features = false }
terl = { path = "../terl" }

[features]
parallel = []
