[workspace]
resolver = "2"

members = ["terl", "py-ir", "py-ast", "pycc-rs", "py-declare", "py-lex"]


[workspace.dependencies]
serde = "1"
serde_json = "1"
either = "1"

[profile.release]
lto = true
strip = true
