[package]
name = "pin1yin1-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin1yin1-parser = { path = "../pin1yin1-parser" }
pin1yin1-ast = { path = "../pin1yin1-ast" }
serde_json = "1"
