[package]
name = "pin1yin1-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt"], optional = true }
serde = { version = "1", optional = true }

[features]
default = ["ser"]
ser = ["serde"]
parallel = ["tokio"]
