[package]
name = "pin1yin1-grammar"
version = "0.1.0"
edition = "2021"

[dependencies]
pin1yin1-parser = { path = "../pin1yin1-parser" }
pin1yin1-ast = { path = "../pin1yin1-ast", features = ["parser"] }
