[package]
name = "pycc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terl = { path = "../terl" }
py-ast = { path = "../py-ast" }
py-ir = { path = "../py-ir", features = ["parser"] }
serde_json = "1"
inkwell = { version = "0.4.0", features = ["llvm17-0-prefer-dynamic"] }
